import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import { MainHeader } from "@/components/MainHeader";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
  weight: ["400", "500", "600"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figtree.variable} antialiased`}
      >
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
